convidados = ['Maria','João','Fernanda','Mateus','Gabriel','Danilo','Jessica','Jonas','Tainara']
print("Os convidados são : " + str(convidados))
print("\nA quantidade de convidadossão:")
print(len(convidados))
print("\nA lista em ordem alfabética é:")
print(sorted(convidados))
print("\nA lista em ordem alfabética inversa é:")
print(sorted(convidados, reverse=True))
print("\nA lista na ordem original é:")
print(convidados)
print("nA lista e ordem inversa a original é:")
convidados.reverse()
print(convidados)
ausentes = convidados.pop()
print(convidados)
print("\nUm convidado saiu!")
print("\nQuem saiu foi: " + str(ausentes))
print("\n")
convidados.insert(0, 'Cassia')
print(convidados)
print("\nUm novo convidado entrou!")
print("\nQuem entrou foi: ")
print(convidados[0])
removidos = convidados.pop(4)
print(convidados)
print("\nQuem foi removido foi: " + removidos)
